name: Check external links

on:
  workflow_dispatch:
  schedule:
    - cron: "17 13 * * 1"

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check URLs in local source data
        run: python3 check_links.py
